name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: platane/snk@master
        with:
          github_user_name: ajay20050412  # Replace with your username
          svg_path: assets/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: assets/github-contribution-grid-snake.svg
          message: 'Update snake.svg'
